---
apiVersion: v1
kind: Service
metadata:
  name: front-end
  #namespace: sock-shop
  annotations:
        prometheus.io/scrape: 'true'
  labels:
    name: front-end
  #namespace: sock-shop
spec:
  type: Loadbalancer
  ports:
  - port: 80
    targetPort: 8079
  selector:
    name: front-end
